=begin
#Grafeas API

#An API to insert and retrieve annotations on cloud artifacts.

OpenAPI spec version: v1alpha1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Grafeas::GrafeasProjectsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GrafeasProjectsApi' do
  before do
    # run before each test
    @instance = Grafeas::GrafeasProjectsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GrafeasProjectsApi' do
    it 'should create an instance of GrafeasProjectsApi' do
      expect(@instance).to be_instance_of(Grafeas::GrafeasProjectsApi)
    end
  end

  # unit tests for create_project
  # Creates a new &#x60;Project&#x60;.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ProtobufEmpty]
  describe 'create_project test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_project
  # Deletes the given &#x60;Project&#x60; from the system.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [ProtobufEmpty]
  describe 'delete_project test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project
  # Returns the requested &#x60;Project&#x60;.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [ApiProject]
  describe 'get_project test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_projects
  # Lists &#x60;Projects&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter The filter expression.
  # @option opts [Integer] :page_size Number of projects to return in the list.
  # @option opts [String] :page_token Token to provide to skip to a particular spot in the list.
  # @return [ApiListProjectsResponse]
  describe 'list_projects test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
