=begin
#Grafeas API

#An API to insert and retrieve annotations on cloud artifacts.

OpenAPI spec version: v1alpha1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'date'

module Grafeas
  class LayerDirective
    
    DIRECTIVE_UNSPECIFIED = 'DIRECTIVE_UNSPECIFIED'.freeze
    MAINTAINER = 'MAINTAINER'.freeze
    RUN = 'RUN'.freeze
    CMD = 'CMD'.freeze
    LABEL = 'LABEL'.freeze
    EXPOSE = 'EXPOSE'.freeze
    ENV = 'ENV'.freeze
    ADD = 'ADD'.freeze
    COPY = 'COPY'.freeze
    ENTRYPOINT = 'ENTRYPOINT'.freeze
    VOLUME = 'VOLUME'.freeze
    USER = 'USER'.freeze
    WORKDIR = 'WORKDIR'.freeze
    ARG = 'ARG'.freeze
    ONBUILD = 'ONBUILD'.freeze
    STOPSIGNAL = 'STOPSIGNAL'.freeze
    HEALTHCHECK = 'HEALTHCHECK'.freeze
    SHELL = 'SHELL'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = LayerDirective.constants.select { |c| LayerDirective::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #LayerDirective" if constantValues.empty?
      value
    end
  end
end
